Fix link in 2017-05-19-Breminale-2017-Vorbereitungen.md
FreifunkBremen/bremen.freifunk.net pull request #143
Opened 2020-09-04 21:40 UTC by Timi7007

See #141.

Elegantere Wege den Link daraus zu kriegen, @SimJoSt?

2020-09-04 21:41 UTC, Timi7007 commented
Siehe auch #142.

2020-09-05 10:22 UTC, SimJoSt commented
> See #141.
> 
> Elegantere Wege den Link daraus zu kriegen, @SimJoSt?

Was genau ist die Frage? Meinst Du mit rauskriegen, wie man den Link darauf entfernt oder ihn in Erfahrung zu bringen? 🙂

2021-01-03 15:42 UTC, lokn commented
Bin für merge.

2021-01-03 20:25 UTC, SimJoSt commented
Mit dem Durchstreichen und dem Update-Kommentar bin ich einverstanden.  
Ich frage mich nur, warum der Link jetzt separat in einer Klammer angezeigt werden soll, statt auf dem Wort "Dudle" zu liegen. Gibt es dafür einen Grund @Timi7007?

2021-01-03 20:26 UTC, SimJoSt requested changes
Mit dem Durchstreichen und dem Update-Kommentar bin ich einverstanden.
Ich frage mich nur, warum der Link jetzt separat in einer Klammer angezeigt werden soll, statt auf dem Wort "Dudle" zu liegen. Gibt es dafür einen Grund @Timi7007?

2021-02-06 12:43 UTC, lokn commented
Link-Ziel entfernt, "Doodle" durchgestrichen und als Link sichtbar gelassen.

2021-02-06 12:44 UTC, merged