add landing page for insta link
FreifunkBremen/bremen.freifunk.net pull request #146
Opened 2020-12-04 14:26 UTC by lokn

Bei Instagram kann man im Profil nur einen Link angeben. Um auf unterschiedliche Inhalte verlinken zu können, ist diese Seite praktisch.

2020-12-04 14:35 UTC, jortgies commented on insta/index.md
> +<a class="btn" href="https://bremen.freifunk.net/blog/2020/03/17/freifunk-hilft.html">Freifunk für Schüler (PDF)</a>
da steht PDF, aber der Blog ist verlinkt. Soll das so?

2020-12-04 14:48 UTC, RadioBBS commented
nö, kann man das anders machen?Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Jan-Eric Ortgies <notifications@github.com> Datum: 04.12.20  15:35  (GMT+01:00) An: "FreifunkBremen/bremen.freifunk.net" <bremen.freifunk.net@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [FreifunkBremen/bremen.freifunk.net] add landing page for insta link (#146) 

@jortgies commented on this pull request.







In insta/index.md:

> @@ -0,0 +1,11 @@

+---

+layout: default

+title: Instagram

+category_id: 0

+---

+## Instagram

+<a class="btn" href="https://bremen.freifunk.net/to/videokonf" target="_blank">Videokonferenz (1.&3. Fr./Monat, 19:30 Uhr)</a>

+

+<a class="btn" href="https://bremen.freifunk.net/blog/2020/03/17/freifunk-hilft.html">Freifunk für Schüler (PDF)</a>



da steht PDF, aber der Blog ist verlinkt. Soll das so?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-04 14:54 UTC, jortgies requested changes

2020-12-04 14:54 UTC, jortgies commented on insta/index.md
> +<a class="btn" href="https://bremen.freifunk.net/blog/2020/03/17/freifunk-hilft.html">Freifunk für Schüler (PDF)</a>
```suggestion
<a class="btn" href="https://bremen.freifunk.net/blog/2020/03/17/freifunk-hilft.html">Freifunk für Schüler (Blogpost)</a>
<a class="btn" href="https://bremen.freifunk.net/blog/files/2020-03-17/Freifunk_Hilft_Schuelern.pdf">Freifunk für Schüler (PDF)</a>
```

2020-12-12 16:13 UTC, genofire commented on insta/index.md
> +<a class="btn" href="https://bremen.freifunk.net/blog/2020/03/17/freifunk-hilft.html">Freifunk für Schüler (PDF)</a>
Im Blogpost sehe ich auf jedenfall eine PDF / Flyer verlinkt

2021-01-03 15:38 UTC, merged