add blog post "B.A.T.M.A.N-Wechsel"
FreifunkBremen/bremen.freifunk.net pull request #150
Opened 2021-02-06 12:33 UTC by lokn

@genofire Stimmt der SSH-Befehl?

2021-02-06 17:15 UTC, oliver requested changes
Danke fürs Schreiben, sieht im großen und ganzen gut aus! Hab noch ein paar Kommentare hinterlassen.

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +- B.A.T.M.A.N v15 und v13 sind nicht kompatibel. Sie meshen nicht. Stelle bitte sicher, dass alle Router, die per Kabel oder WLAN mit deinem Router meshen, die gleiche Domain ausgewählt haben.
Das Stichwort "Domain" sollte vorher einmal irgendwo erklärt worden sein. Ein weiterer Satz oberhalb von "__Hinweis__" wär da wohl ganz gut.

Vielleicht sowas hier: "Es gibt bereits einen eigenen VPN-Server für B.A.T.M.A.N v15; du musst in deinem Testing-Router nur die entsprechende "Domain" einstellen, damit dieser Server verwendet wird."

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +1. Halte den Reset-Knopf etwa 10 Sekunden gedrückt bis alle Lämpchen kurz aufblinken.
```suggestion
1. Halte den Reset-Knopf etwa 10 Sekunden gedrückt, bis alle Lämpchen kurz aufblinken.
```

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +Um unter anderem eine Vielzahl neuer Geräte zu unterstützen, wollen wir auf Gluon 2020 wechseln. Gluon ist die Grundlage unsere Bremer Freifunk-Firmware.
```suggestion
Um unter anderem eine Vielzahl neuer Geräte zu unterstützen, wollen wir auf Gluon 2020 wechseln. Gluon ist die Grundlage unserer Bremer Freifunk-Firmware.
```

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +    uci set gluon.core.domain='ffhb_batv15' && gluon-reconfigure && gluon-reload &&  uci commit
@genofire: muss ich danach rebooten? Oder ist diese Änderung sofort aktiv?

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +Eine Website zu öffnen ist für uns meist nur einen Klick entfernt. Technisch gesehen, sind es dutzende kleine Schritte. Damit die Website durch das Freifunk-Netz zu dir geschickt werden kann, muss de
Fürs Review ist es einfacher, wenn du jeden Satz auf eine eigene Zeile schreibst. Im sichtbaren Text sollte das keine Auswirkungen haben, aber wir können dann einfacher Kommentare an bestimmte Stellen packen.

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +Eine Website zu öffnen ist für uns meist nur einen Klick entfernt. Technisch gesehen, sind es dutzende kleine Schritte. Damit die Website durch das Freifunk-Netz zu dir geschickt werden kann, muss de
Du könntest "B.A.T.M.A.N" mit https://www.open-mesh.org/projects/open-mesh/wiki verlinken.

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +Um unter anderem eine Vielzahl neuer Geräte zu unterstützen, wollen wir auf Gluon 2020 wechseln. Gluon ist die Grundlage unsere Bremer Freifunk-Firmware.
Du könntest "Gluon" mit https://wiki.freifunk.net/Gluon verlinken.

2021-02-06 17:15 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +
Was hältst du von einem kurzen Satz dazu, wie es weitergehen soll? So in der Richtung "Sobald das neue Batman-System ausreichend getestet ist, werden wir die Umstellung des ganzen Bremer Freifunk-Netzes angehen. Das soll so ähnlich ablaufen wie bei der Umstellung auf 11s (Link: https://ffhb.de/blog/2020/01/23/wechsel-von-ibss-zu-11s.html). Dazu wird es aber noch ein weiteres Blogpost geben."

2021-02-11 20:47 UTC, oliver commented
Bin grad nicht sicher, deshalb die Nachfrage: wollen wir den Text hier auf Github weiter bearbeiten, oder auf der Wiki-Seite?

2021-02-11 20:51 UTC, oliver commented on _posts/2021-02-07-batman-wechsel.md
> +2. Öffne die Seite _http://192.168.1.1/_
Hier sollte noch irgendwo stehen, dass man sich per LAN-Kabel mit dem Knoten verbinden sollte.

Und hier könnte auch noch ein Link z.B. auf https://ffhb.de/anleitungen.html#konfigurationsmodus hin, wo der Wechsel in den Konfig-Modus ausführlich beschrieben ist.

2021-02-16 12:16 UTC, lokn commented on _posts/2021-02-07-batman-wechsel.md
> +- Remote first.
Steht da am Anfang, damit das möglichst viele lesen und den Abschnitt nicht überspringen.

2021-02-16 12:41 UTC, lokn commented
Offline SSID funktioniert nicht mehr. Wollen wir das erwähnen?

2021-09-28 13:54 UTC, mortzu commented
> Offline SSID funktioniert nicht mehr. Wollen wir das erwähnen?

Ja

2021-09-28 13:54 UTC, mortzu commented
Fehlende Änderungen einpflegen -> merge

2021-12-04 11:20 UTC, lokn commented on _posts/2021-02-07-batman-wechsel.md
> +    uci set gluon.core.domain='ffhb_batv15' && gluon-reconfigure && gluon-reload &&  uci commit
Kein Neustart nötig

2022-07-23 20:04 UTC, genofire commented on _posts/2021-02-07-batman-wechsel.md
> +    uci set gluon.core.domain='ffhb_batv15' && gluon-reconfigure && gluon-reload &&  uci commit
eigentlich kein neustart notwendig - allerdings hab ich bereits 1-2 schlechte Erfahrungen (kA mehr welche), die mit ein reboot solved wurden.

2022-07-23 20:06 UTC, genofire commented
irgendwas ist hier mit den merge request eklig geworden ...

mag wer die Ängerungen ggf. in ein neue branch + merge request kopieren?

2022-07-24 13:13 UTC, oliver commented
Die Batman-Umstellung ist ja nun passiert 🎉️ also hat sich dieser Blogpost-Entwurf wohl erledigt. Ich schließ den also mal.

2022-07-24 13:13 UTC, closed without merging