feat(post): add release stabil 2021 and testing 2023
FreifunkBremen/bremen.freifunk.net pull request #160
Opened 2023-08-20 08:02 UTC by genofire

2023-08-20 08:30 UTC, mortzu commented on _posts/2023-07-20-release-2021.md
> +Nachdem die Testing-Firmware [2021.1.2+bremen1](https://wiki.bremen.freifunk.net/Firmware/Changelog.md#2021-1-2-bremen1) nun seit acht Monate ohne schwerwigende Probleme im Einsatz ist,
Monaten

2023-08-20 08:34 UTC, mortzu commented on _posts/2023-07-20-release-2021.md
> + diese Version zur Stable-Firmware zu befördern.
Der Satz macht irgendwie keinen Sinn...

2023-08-20 08:35 UTC, mortzu commented on _posts/2023-07-20-release-2021.md
> +Doch viel wichtiger, die noch ca. 46 Stück des TP-Link WR841 bekommen hiermit letztes Update.
Doch viel wichtiger: Die noch...

2023-08-20 08:38 UTC, mortzu commented on _posts/2023-07-20-release-2021.md
> +Wir haben zwar bereits in [Zukunft des TP-Link WR841](/blog/2020/07/21/zukunft-841.html) im Jahre 2020 davor gewarnt.
Wir haben bereits in [Zukunft des TP-Link WR841](/blog/2020/07/21/zukunft-841.html) im Jahre 2020 davor gewarnt, nun ist es so weit: Die 4MB Flash und 32MB RAM Modelle haben ab jetzt quasi ausgedient. Damit bekommen die ~46 verbliebenen TP-Link WR841 hiermit ihr letztes Update.

2023-08-20 08:39 UTC, mortzu commented on _posts/2023-07-20-release-2021.md
> +Neben der neuen Stable-Version gibt es jetzt mit der [2023.1+bremen1](https://wiki.bremen.freifunk.net/Firmware/Changelog.md#2023-1-bremen1) auch schon wieder eine neue Testing-Version.
"testing"-Version oder Testing-Version

2023-08-20 08:39 UTC, mortzu commented on _posts/2023-07-20-release-2021.md
> +Hierdurch geht Support für die Geräte mit wenig Memory und Flash verloren, doch genauso viele neue Geräte werden nun ebenfalls unterstützt.
Memory oder RAM?

2023-09-02 10:47 UTC, oliver requested changes
@genofire : danke dir für den Text! Find das im großen und ganzen gut; hab noch ein paar Kommentare/Änderungsvorschläge reingeschrieben.

2023-09-02 10:47 UTC, oliver commented on _posts/2023-07-20-release-2021.md
> +Damit bekommen die ~46 verbliebenen des TP-Link WR841 hiermit ihr letztes Update.
Unter https://gluon.readthedocs.io/en/latest/releases/v2022.1.html#removed-devices sind die Geräte aufgelistet, die nicht mehr unterstützt werden. Ich würd mal schätzen, dass zusätzlich zu den 133 841ern noch 30-40 andere Router in unserem Netz nicht mehr unterstützt werden (also diverse TP-Link WA-... und WR-...-Modelle).

Vorschlag also:
```suggestion
Damit bekommen die ~130 verbliebenen des TP-Link WR841 und die ~40 anderen [ähnlichen betroffenen Modelle](https://gluon.readthedocs.io/en/latest/releases/v2022.1.html#removed-devices) hiermit ihr letztes Update.
```

2023-09-06 13:41 UTC, genofire commented on _posts/2023-07-20-release-2021.md
> +Damit bekommen die ~46 verbliebenen des TP-Link WR841 hiermit ihr letztes Update.
ups, hab da wohl nur auf eine version von 841 geschaut - danke für die neue aufrechnung

2023-09-06 22:35 UTC, genofire commented on _posts/2023-07-20-release-2021.md
> +title:  "Firmware 2021 - letzte mit 8MB support"
Hast natürlich recht - war ein mix in mein Kopf von 8MB ist okay und 4MB und kleier ist zu klein (bin etwas raus)

2023-09-08 05:12 UTC, oliver commented on _posts/2023-09-08-release-2021.md
> +
Hab durch Zufall auf https://map.ffhb.de gesehen, dass die 2023er-Firmware noch auf keinem einzigen Gerät im Netz drauf ist! Das find ich nicht gut, die FW ohne so einen grundlegenden Test auf 50 Geräte auszurollen.

Ich bin dafür, den Absatz über die neue Testing-FW rauszunehmen. Wir können den Text ja für einen weiteren Blogpost verwenden.

```suggestion
```

2023-09-09 07:04 UTC, oliver requested changes

2023-09-09 07:04 UTC, oliver commented on _posts/2023-09-08-release-2021.md
> +Die neue "stable"-Version wird seit Dienstag automatisch auf allen Knoten im Bremer Freifunk-Netz installiert,
```suggestion
Die neue "stable"-Version wird ab Dienstag automatisch auf allen Knoten im Bremer Freifunk-Netz installiert,
```

2023-09-09 07:04 UTC, oliver commented on _posts/2023-09-08-release-2021.md
> +date:   2023-09-08 20:08:00 +0100
```suggestion
date:   2023-09-09 10:08:00 +0100
```

2023-09-09 07:07 UTC, merged